const MAX_WINDOW_MINUTES=24*60; let storedComments=[],comments=[],mutedUsers=[],learningAutoMutedUsers=[],selected=null,windowMinutes=60,historyTargetTabId=null,learningResult=null,learningLastRun=0;
const DEFAULT_MODERATION={enabled:false,rateEnabled:true,rateCount:8,rateWindowSec:30,duplicateEnabled:true,duplicateCount:3,duplicateWindowSec:60,ngEnabled:true,ngWords:[],whitelistUsers:[],learningEnabled:false,learningMinComments:5,learningMinMutedUsers:3,learningMaxCommentsPerUser:40,learningCandidateThreshold:0.25,learningAutoMute:false,learningAutoMuteThreshold:0.40,learningNormalPenalty:0.75};
const STORAGE_SCHEMA_VERSION=1;
const TRANSFER_FORMAT='abema-comment-analyzer-transfer';
const TRANSFER_KEYS=['comments','mutedUsers','learningAutoMutedUsers','analysisWindowMinutes','moderationSettings','autoMuteLog','captureEnabled','lastCommentAt'];
const $=id=>document.getElementById(id);
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function commentTime(c){return Number(c.createdAtMs||c.observedAt||0);}
function analysisAnchor(){const times=storedComments.map(commentTime).filter(Boolean);return times.length?Math.max(...times):Date.now();}
function formatDuration(minutes){if(minutes<60)return`${minutes}分`;if(minutes%60===0)return`${minutes/60}時間`;return`${Math.floor(minutes/60)}時間${minutes%60}分`;}
function currentWindowFromControls(){const value=Math.max(1,Number($('windowValue').value)||1);const unit=Number($('windowUnit').value)||1;return Math.min(MAX_WINDOW_MINUTES,Math.round(value*unit));}
function syncControlsFromMinutes(minutes){if(minutes>=60&&minutes%60===0){$('windowValue').value=minutes/60;$('windowUnit').value='60';}else{$('windowValue').value=minutes;$('windowUnit').value='1';}}
function lines(v){return String(v||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);}
function renderModerationSettings(settings){const s={...DEFAULT_MODERATION,...(settings||{})};$('modEnabled').checked=!!s.enabled;$('rateEnabled').checked=!!s.rateEnabled;$('rateCount').value=s.rateCount;$('rateWindowSec').value=s.rateWindowSec;$('duplicateEnabled').checked=!!s.duplicateEnabled;$('duplicateCount').value=s.duplicateCount;$('duplicateWindowSec').value=s.duplicateWindowSec;$('ngEnabled').checked=!!s.ngEnabled;$('ngWords').value=(s.ngWords||[]).join('\n');$('whitelistUsers').value=(s.whitelistUsers||[]).join('\n');$('learningEnabled').checked=!!s.learningEnabled;$('learningMinComments').value=s.learningMinComments;$('learningMinMutedUsers').value=s.learningMinMutedUsers;$('learningCandidateThreshold').value=Math.round(Number(s.learningCandidateThreshold||0.58)*100);$('learningAutoMute').checked=!!s.learningAutoMute;$('learningAutoMuteThreshold').value=Math.round(Number(s.learningAutoMuteThreshold||0.78)*100);}
function renderAutoMuteLog(log){const items=Array.isArray(log)?[...log].reverse():[];$('autoMuteLog').innerHTML=items.length?items.slice(0,100).map(x=>`<div style="padding:7px 0;border-top:1px solid #333"><b>${escapeHtml(x.userId)}</b> — ${escapeHtml(x.reason)}<br><span style="color:#aaa">${new Date(x.mutedAt||Date.now()).toLocaleString()} / ${escapeHtml(x.message||'')}</span></div>`).join(''):'自動ミュート履歴はありません。';}
function setTransferStatus(message,isError=false){const el=$('transferStatus');el.textContent=message;el.style.color=isError?'#f99':'#aaa';}
function renderLearningCandidates(settings,force=false){const box=$('learningCandidates'),status=$('learningStatus'),cfg={...DEFAULT_MODERATION,...(settings||{})};if(!cfg.learningEnabled){learningResult=null;box.innerHTML='';status.textContent='学習型ミュートは無効です。';return;}if(!globalThis.ABEMACommentLearning){box.innerHTML='';status.textContent='学習モデルを読み込めませんでした。';return;}const now=Date.now();if(force||!learningResult||now-learningLastRun>=10000){const learnedAuto=new Set(learningAutoMutedUsers);const trainingMuted=mutedUsers.filter(id=>!learnedAuto.has(id));learningResult=ABEMACommentLearning.analyze(storedComments,trainingMuted,cfg.whitelistUsers||[],cfg);learningLastRun=now;}if(!learningResult.ready){box.innerHTML='';status.textContent=learningResult.reason||'学習データが不足しています。';return;}const auto=cfg.learningAutoMute?` / 自動ミュート ${Math.round(Number(cfg.learningAutoMuteThreshold||0.78)*100)}%以上`:' / 候補表示のみ';status.textContent=`学習元 ${learningResult.trainingUsers}人 / 比較対象 ${learningResult.normalUsers||0}人 / 候補 ${learningResult.candidates.length}人${auto}`;box.innerHTML=learningResult.candidates.length?learningResult.candidates.slice(0,50).map(x=>`<div style="padding:8px 0;border-top:1px solid #333"><b>${escapeHtml(x.userId)}</b> — 類似度 <b>${(x.score*100).toFixed(1)}%</b> / ${x.commentCount}件 <button data-learnmute="${escapeHtml(x.userId)}">ミュート</button> <button data-learnwhite="${escapeHtml(x.userId)}">除外</button><br><span style="color:#aaa">特徴: ${escapeHtml((x.patterns||[]).join(' / ')||'-')}</span></div>`).join(''):'候補はありません。';document.querySelectorAll('[data-learnmute]').forEach(b=>b.onclick=async()=>{const uid=b.dataset.learnmute;if(!mutedUsers.includes(uid))await toggleMute(uid);learningLastRun=0;});document.querySelectorAll('[data-learnwhite]').forEach(b=>b.onclick=async()=>{const uid=b.dataset.learnwhite;const d=await chrome.storage.local.get('moderationSettings');const next={...DEFAULT_MODERATION,...(d.moderationSettings||{})};next.whitelistUsers=[...new Set([...(next.whitelistUsers||[]).map(String),uid])];learningLastRun=0;await chrome.storage.local.set({moderationSettings:next});});}
async function ensureStorageSchema(){const manifest=chrome.runtime.getManifest();const d=await chrome.storage.local.get(['storageSchemaVersion','installedExtensionVersion']);const current=Number(d.storageSchemaVersion)||0;if(current>STORAGE_SCHEMA_VERSION){setTransferStatus(`このデータは新しい保存形式 v${current} です。拡張機能を最新版へ更新してください。`,true);return;}if(current<STORAGE_SCHEMA_VERSION){await chrome.storage.local.set({storageSchemaVersion:STORAGE_SCHEMA_VERSION,lastSchemaMigrationAt:Date.now(),lastSchemaMigrationFrom:current});}if(d.installedExtensionVersion!==manifest.version){await chrome.storage.local.set({installedExtensionVersion:manifest.version,lastVersionUpgradeAt:Date.now(),previousExtensionVersion:d.installedExtensionVersion||null});}$('versionInfo').textContent=`v${manifest.version} / 保存形式 ${STORAGE_SCHEMA_VERSION}`;}
async function exportTransfer(){try{const all=await chrome.storage.local.get(TRANSFER_KEYS);const data={};for(const key of TRANSFER_KEYS)if(Object.prototype.hasOwnProperty.call(all,key))data[key]=all[key];const manifest=chrome.runtime.getManifest();const payload={format:TRANSFER_FORMAT,schemaVersion:STORAGE_SCHEMA_VERSION,extensionVersion:manifest.version,exportedAt:new Date().toISOString(),data};const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/T/,'-').replace(/\..+$/,'');download(`abema-comment-analyzer-transfer-v${manifest.version}-${stamp}.json`,JSON.stringify(payload,null,2),'application/json');setTransferStatus(`引継ぎファイルを書き出しました。コメント ${Array.isArray(data.comments)?data.comments.length:0}件、ミュート ${(data.mutedUsers||[]).length}件を含みます。`);}catch(e){setTransferStatus(`書き出しに失敗しました: ${e.message||e}`,true);}}
async function importTransferFile(file){try{if(!file)return;const text=await file.text();const payload=JSON.parse(text);if(!payload||payload.format!==TRANSFER_FORMAT||!payload.data||typeof payload.data!=='object')throw new Error('ABEMA Comment Analyzerの引継ぎファイルではありません');const schema=Number(payload.schemaVersion)||0;if(schema>STORAGE_SCHEMA_VERSION)throw new Error(`引継ぎデータの保存形式 v${schema} はこの拡張では新しすぎます。先に最新版へ更新してください`);const restore={};for(const key of TRANSFER_KEYS)if(Object.prototype.hasOwnProperty.call(payload.data,key))restore[key]=payload.data[key];restore.storageSchemaVersion=STORAGE_SCHEMA_VERSION;restore.lastTransferImportAt=Date.now();restore.lastTransferSourceVersion=String(payload.extensionVersion||'unknown');await chrome.storage.local.set(restore);setTransferStatus(`引継ぎ完了: v${payload.extensionVersion||'?'} のデータを復元しました。コメント ${Array.isArray(restore.comments)?restore.comments.length:0}件、ミュート ${(restore.mutedUsers||[]).length}件。`);await load();}catch(e){setTransferStatus(`引継ぎに失敗しました: ${e.message||e}`,true);}finally{$('transferFile').value='';}}
async function load(){const d=await chrome.storage.local.get(['comments','mutedUsers','learningAutoMutedUsers','analysisWindowMinutes','historyLoadProgress','moderationSettings','autoMuteLog']);storedComments=Array.isArray(d.comments)?d.comments:[];mutedUsers=(d.mutedUsers||[]).map(String);learningAutoMutedUsers=(d.learningAutoMutedUsers||[]).map(String);windowMinutes=Math.min(MAX_WINDOW_MINUTES,Math.max(1,Number(d.analysisWindowMinutes)||60));syncControlsFromMinutes(windowMinutes);renderHistoryStatus(d.historyLoadProgress);renderModerationSettings(d.moderationSettings);renderAutoMuteLog(d.autoMuteLog);renderLearningCandidates(d.moderationSettings);applyFilter();}
function applyFilter(){const anchor=analysisAnchor(),span=windowMinutes*60000;comments=storedComments.filter(c=>{const t=commentTime(c);return t&&anchor-t>=0&&anchor-t<=span;});render();}
function groups(){const m=new Map();for(const c of comments){const u=String(c.userId||'unknown');if(!m.has(u))m.set(u,[]);m.get(u).push(c);}return[...m].map(([userId,list])=>({userId,list,count:list.length})).sort((a,b)=>b.count-a.count);}
function avgGap(list){if(list.length<2)return'-';const t=list.map(commentTime).sort((a,b)=>a-b);let s=0;for(let i=1;i<t.length;i++)s+=t[i]-t[i-1];const sec=s/(t.length-1)/1000;return sec<60?`${sec.toFixed(1)}秒`:`${(sec/60).toFixed(1)}分`;}
function render(){const gs=groups();$('total').textContent=comments.length;$('unique').textContent=gs.length;$('muted').textContent=mutedUsers.length;const top=gs.slice(0,10).reduce((s,g)=>s+g.count,0);$('topShare').textContent=comments.length?`${(top/comments.length*100).toFixed(1)}%`:'0%';$('timelineTitle').textContent=`最新コメント基準・直近${formatDuration(windowMinutes)}のコメント数推移`;renderAvailableSpan();renderTimeline();renderUsers(gs);if(selected)renderDetail(selected);}
function renderAvailableSpan(){if(!storedComments.length){$('availableSpan').textContent='保存データなし';return;}const times=storedComments.map(commentTime).filter(Boolean);if(!times.length){$('availableSpan').textContent='保存データなし';return;}const oldest=Math.min(...times),newest=Math.max(...times);const mins=Math.max(1,Math.round((newest-oldest)/60000));$('availableSpan').textContent=`保存中: ${formatDuration(mins)} / ${storedComments.length}件 / 最新 ${new Date(newest).toLocaleString()}`;}
function renderUsers(gs){const q=$('search').value.toLowerCase();$('usersBody').innerHTML=gs.filter(g=>!q||g.userId.toLowerCase().includes(q)||g.list.some(c=>String(c.message||'').toLowerCase().includes(q))).map(g=>`<tr data-user="${escapeHtml(g.userId)}"><td>${escapeHtml(g.userId)}</td><td>${g.count}</td><td>${comments.length?(g.count/comments.length*100).toFixed(1):0}%</td><td>${avgGap(g.list)}</td><td><button class="mute" data-mute="${escapeHtml(g.userId)}">${mutedUsers.includes(g.userId)?'解除':'ミュート'}</button></td></tr>`).join('');document.querySelectorAll('tr[data-user]').forEach(tr=>tr.onclick=e=>{if(e.target.dataset.mute)return;selected=tr.dataset.user;renderDetail(selected);});document.querySelectorAll('[data-mute]').forEach(b=>b.onclick=async e=>{e.stopPropagation();await toggleMute(b.dataset.mute);});}
async function toggleMute(uid){const set=new Set(mutedUsers),learned=new Set(learningAutoMutedUsers);if(set.has(uid)){set.delete(uid);learned.delete(uid);}else{set.add(uid);learned.delete(uid);}mutedUsers=[...set];learningAutoMutedUsers=[...learned];learningLastRun=0;await chrome.storage.local.set({mutedUsers,learningAutoMutedUsers,learningRebuildRequest:Date.now()});render();}
function renderDetail(uid){const list=comments.filter(c=>String(c.userId)===uid).sort((a,b)=>commentTime(a)-commentTime(b));$('detailTitle').textContent=uid;$('detailMeta').innerHTML=`${list.length}件 / 平均間隔 ${avgGap(list)} <button class="mute" id="detailMute">${mutedUsers.includes(uid)?'ミュート解除':'この投稿者をミュート'}</button>`;$('detailComments').innerHTML=list.map(c=>`<div class="comment"><span class="time">${new Date(commentTime(c)).toLocaleTimeString()}</span><span class="msg">${escapeHtml(c.message)}</span></div>`).join('');$('detailMute').onclick=()=>toggleMute(uid);}
function renderTimeline(){const cv=$('timeline'),ctx=cv.getContext('2d');const w=cv.width,h=cv.height;ctx.clearRect(0,0,w,h);const binCount=12,bins=Array(binCount).fill(0),anchor=analysisAnchor(),span=windowMinutes*60000,binMs=span/binCount;for(const c of comments){const age=anchor-commentTime(c);const idx=binCount-1-Math.floor(age/binMs);if(idx>=0&&idx<binCount)bins[idx]++;}const max=Math.max(1,...bins);ctx.fillStyle='#ccc';ctx.font='12px system-ui';for(let i=0;i<binCount;i++){const x=40+i*((w-60)/(binCount-1)),barH=(bins[i]/max)*(h-55);ctx.fillRect(x-12,h-28-barH,24,barH);ctx.fillText(String(bins[i]),x-7,h-34-barH);ctx.fillStyle='#777';const remaining=Math.round(windowMinutes-(i*(windowMinutes/(binCount-1))));const label=remaining>=60?`${(remaining/60).toFixed(remaining%60?1:0)}h`:`${remaining}m`;ctx.fillText(label,x-14,h-8);ctx.fillStyle='#ccc';}}
function renderHistoryStatus(p){const el=$('historyStatus');if(!p){el.textContent='過去コメントを取得する場合は、ABEMAでコメント欄を表示した状態で「過去コメントを読み込む」を押してください。';$('cancelHistory').style.display='none';return;}const running=p.status==='running'||p.status==='starting';$('cancelHistory').style.display=running?'inline-block':'none';const oldest=p.oldestAt?` / 最古 ${new Date(p.oldestAt).toLocaleTimeString()}`:'';el.textContent=`${p.message||p.status}${oldest}`;}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function findAbemaTab(){const tabs=await chrome.tabs.query({url:'https://abema.tv/*'});if(!tabs.length)return null;return tabs.find(t=>t.active)||tabs[0];}
$('exportTransfer').onclick=exportTransfer;$('importTransfer').onclick=()=>$('transferFile').click();$('transferFile').onchange=e=>importTransferFile(e.target.files?.[0]);
$('saveModeration').onclick=async()=>{const settings={enabled:$('modEnabled').checked,rateEnabled:$('rateEnabled').checked,rateCount:Math.max(2,Number($('rateCount').value)||8),rateWindowSec:Math.max(1,Number($('rateWindowSec').value)||30),duplicateEnabled:$('duplicateEnabled').checked,duplicateCount:Math.max(2,Number($('duplicateCount').value)||3),duplicateWindowSec:Math.max(1,Number($('duplicateWindowSec').value)||60),ngEnabled:$('ngEnabled').checked,ngWords:lines($('ngWords').value),whitelistUsers:lines($('whitelistUsers').value),learningEnabled:$('learningEnabled').checked,learningMinComments:Math.max(2,Number($('learningMinComments').value)||5),learningMinMutedUsers:Math.max(1,Number($('learningMinMutedUsers').value)||3),learningMaxCommentsPerUser:40,learningCandidateThreshold:Math.max(0.01,Math.min(0.99,(Number($('learningCandidateThreshold').value)||25)/100)),learningAutoMute:$('learningAutoMute').checked,learningAutoMuteThreshold:Math.max(0.01,Math.min(1,(Number($('learningAutoMuteThreshold').value)||40)/100)),learningNormalPenalty:0.75};learningLastRun=0;await chrome.storage.local.set({moderationSettings:settings,learningRebuildRequest:Date.now()});$('moderationSaved').textContent='保存しました';renderLearningCandidates(settings,true);setTimeout(()=>$('moderationSaved').textContent='',1800);};
$('applyWindow').onclick=async()=>{windowMinutes=currentWindowFromControls();await chrome.storage.local.set({analysisWindowMinutes:windowMinutes});syncControlsFromMinutes(windowMinutes);applyFilter();};
$('loadHistory').onclick=async()=>{const id=Date.now();const tab=await findAbemaTab();if(!tab?.id){const p={status:'error',requestId:id,message:'ABEMAタブが見つかりません。ABEMAを開いてコメント欄を表示してください。',updatedAt:id};await chrome.storage.local.set({historyLoadProgress:p});renderHistoryStatus(p);return;}historyTargetTabId=tab.id;const p={status:'starting',requestId:id,message:`ABEMAタブを検出しました。取得開始: ${tab.title||'ABEMA'}`,updatedAt:id};await chrome.storage.local.set({historyLoadProgress:p});renderHistoryStatus(p);try{await chrome.tabs.sendMessage(tab.id,{source:'abema-comment-analyzer',type:'LOAD_HISTORY_REQUEST',requestId:id});}catch(e){const err={status:'error',requestId:id,message:'ABEMAタブへ接続できません。ABEMAタブを再読み込みしてから再試行してください。',updatedAt:Date.now()};await chrome.storage.local.set({historyLoadProgress:err});renderHistoryStatus(err);}};
$('cancelHistory').onclick=async()=>{if(!historyTargetTabId){const tab=await findAbemaTab();historyTargetTabId=tab?.id||null;}if(historyTargetTabId)try{await chrome.tabs.sendMessage(historyTargetTabId,{source:'abema-comment-analyzer',type:'CANCEL_HISTORY_REQUEST',requestId:Date.now()});}catch(_){};};
$('refresh').onclick=load;$('search').oninput=()=>renderUsers(groups());$('exportJson').onclick=()=>download('abema-comments.json',JSON.stringify(comments,null,2),'application/json');$('exportCsv').onclick=()=>{const q=s=>`"${String(s??'').replaceAll('"','""')}"`;download('abema-comments.csv',['time,userId,message,pageTitle',...comments.map(c=>[new Date(commentTime(c)).toISOString(),c.userId,c.message,c.pageTitle].map(q).join(','))].join('\n'),'text/csv');};chrome.storage.onChanged.addListener((c,a)=>{if(a!=='local')return;if(c.comments||c.mutedUsers||c.learningAutoMutedUsers||c.moderationSettings||c.autoMuteLog)load();if(c.historyLoadProgress)renderHistoryStatus(c.historyLoadProgress.newValue);});
(async()=>{await ensureStorageSchema();await load();})();
