const HOUR=3600000; let comments=[], mutedUsers=[], selected=null;
const $=id=>document.getElementById(id);
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function load(){const d=await chrome.storage.local.get(['comments','mutedUsers']); const now=Date.now();comments=(d.comments||[]).filter(c=>now-(c.observedAt||c.createdAtMs)<=HOUR);mutedUsers=(d.mutedUsers||[]).map(String);render();}
function groups(){const m=new Map();for(const c of comments){const u=String(c.userId||'unknown');if(!m.has(u))m.set(u,[]);m.get(u).push(c);}return [...m].map(([userId,list])=>({userId,list,count:list.length})).sort((a,b)=>b.count-a.count);}
function avgGap(list){if(list.length<2)return '-';const t=list.map(c=>c.createdAtMs||c.observedAt).sort((a,b)=>a-b);let s=0;for(let i=1;i<t.length;i++)s+=t[i]-t[i-1];const sec=s/(t.length-1)/1000;return sec<60?`${sec.toFixed(1)}秒`:`${(sec/60).toFixed(1)}分`;}
function render(){const gs=groups();$('total').textContent=comments.length;$('unique').textContent=gs.length;$('muted').textContent=mutedUsers.length;const top=gs.slice(0,10).reduce((s,g)=>s+g.count,0);$('topShare').textContent=comments.length?`${(top/comments.length*100).toFixed(1)}%`:'0%';renderTimeline();renderUsers(gs);if(selected)renderDetail(selected);}
function renderUsers(gs){const q=$('search').value.toLowerCase();$('usersBody').innerHTML=gs.filter(g=>!q||g.userId.toLowerCase().includes(q)||g.list.some(c=>c.message.toLowerCase().includes(q))).map(g=>`<tr data-user="${escapeHtml(g.userId)}"><td>${escapeHtml(g.userId)}</td><td>${g.count}</td><td>${comments.length?(g.count/comments.length*100).toFixed(1):0}%</td><td>${avgGap(g.list)}</td><td><button class="mute" data-mute="${escapeHtml(g.userId)}">${mutedUsers.includes(g.userId)?'解除':'ミュート'}</button></td></tr>`).join('');document.querySelectorAll('tr[data-user]').forEach(tr=>tr.onclick=e=>{if(e.target.dataset.mute)return;selected=tr.dataset.user;renderDetail(selected);});document.querySelectorAll('[data-mute]').forEach(b=>b.onclick=async e=>{e.stopPropagation();await toggleMute(b.dataset.mute);});}
async function toggleMute(uid){const set=new Set(mutedUsers);set.has(uid)?set.delete(uid):set.add(uid);mutedUsers=[...set];await chrome.storage.local.set({mutedUsers});render();}
function renderDetail(uid){const list=comments.filter(c=>String(c.userId)===uid).sort((a,b)=>(a.createdAtMs||a.observedAt)-(b.createdAtMs||b.observedAt));$('detailTitle').textContent=uid;$('detailMeta').innerHTML=`${list.length}件 / 平均間隔 ${avgGap(list)} <button class="mute" id="detailMute">${mutedUsers.includes(uid)?'ミュート解除':'この投稿者をミュート'}</button>`;$('detailComments').innerHTML=list.map(c=>`<div class="comment"><span class="time">${new Date(c.createdAtMs||c.observedAt).toLocaleTimeString()}</span><span class="msg">${escapeHtml(c.message)}</span></div>`).join('');$('detailMute').onclick=()=>toggleMute(uid);}
function renderTimeline(){const cv=$('timeline'),ctx=cv.getContext('2d');const w=cv.width,h=cv.height;ctx.clearRect(0,0,w,h);const bins=Array(12).fill(0),now=Date.now();for(const c of comments){const age=now-(c.observedAt||c.createdAtMs);const idx=11-Math.floor(age/300000);if(idx>=0&&idx<12)bins[idx]++;}const max=Math.max(1,...bins);ctx.fillStyle='#ccc';ctx.font='12px system-ui';for(let i=0;i<12;i++){const x=40+i*((w-60)/11),barH=(bins[i]/max)*(h-55);ctx.fillRect(x-12,h-28-barH,24,barH);ctx.fillText(String(bins[i]),x-7,h-34-barH);ctx.fillStyle='#777';ctx.fillText(`${55-i*5}分`,x-14,h-8);ctx.fillStyle='#ccc';}}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('refresh').onclick=load;$('search').oninput=()=>renderUsers(groups());$('exportJson').onclick=()=>download('abema-comments.json',JSON.stringify(comments,null,2),'application/json');$('exportCsv').onclick=()=>{const q=s=>`"${String(s??'').replaceAll('"','""')}"`;download('abema-comments.csv',['time,userId,message,pageTitle',...comments.map(c=>[new Date(c.createdAtMs||c.observedAt).toISOString(),c.userId,c.message,c.pageTitle].map(q).join(','))].join('\n'),'text/csv');};chrome.storage.onChanged.addListener((c,a)=>{if(a==='local'&&(c.comments||c.mutedUsers))load();});load();
