const MAX_WINDOW_MINUTES=24*60; let storedComments=[],comments=[],mutedUsers=[],selected=null,windowMinutes=60;
const $=id=>document.getElementById(id);
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function commentTime(c){return Number(c.observedAt||c.createdAtMs||0);}
function formatDuration(minutes){if(minutes<60)return`${minutes}分`;if(minutes%60===0)return`${minutes/60}時間`;return`${Math.floor(minutes/60)}時間${minutes%60}分`;}
function currentWindowFromControls(){const value=Math.max(1,Number($('windowValue').value)||1);const unit=Number($('windowUnit').value)||1;return Math.min(MAX_WINDOW_MINUTES,Math.round(value*unit));}
function syncControlsFromMinutes(minutes){if(minutes>=60&&minutes%60===0){$('windowValue').value=minutes/60;$('windowUnit').value='60';}else{$('windowValue').value=minutes;$('windowUnit').value='1';}}
async function load(){const d=await chrome.storage.local.get(['comments','mutedUsers','analysisWindowMinutes','historyLoadProgress']);storedComments=Array.isArray(d.comments)?d.comments:[];mutedUsers=(d.mutedUsers||[]).map(String);windowMinutes=Math.min(MAX_WINDOW_MINUTES,Math.max(1,Number(d.analysisWindowMinutes)||60));syncControlsFromMinutes(windowMinutes);renderHistoryStatus(d.historyLoadProgress);applyFilter();}
function applyFilter(){const now=Date.now(),span=windowMinutes*60000;comments=storedComments.filter(c=>{const t=commentTime(c);return t&&now-t<=span;});render();}
function groups(){const m=new Map();for(const c of comments){const u=String(c.userId||'unknown');if(!m.has(u))m.set(u,[]);m.get(u).push(c);}return[...m].map(([userId,list])=>({userId,list,count:list.length})).sort((a,b)=>b.count-a.count);}
function avgGap(list){if(list.length<2)return'-';const t=list.map(commentTime).sort((a,b)=>a-b);let s=0;for(let i=1;i<t.length;i++)s+=t[i]-t[i-1];const sec=s/(t.length-1)/1000;return sec<60?`${sec.toFixed(1)}秒`:`${(sec/60).toFixed(1)}分`;}
function render(){const gs=groups();$('total').textContent=comments.length;$('unique').textContent=gs.length;$('muted').textContent=mutedUsers.length;const top=gs.slice(0,10).reduce((s,g)=>s+g.count,0);$('topShare').textContent=comments.length?`${(top/comments.length*100).toFixed(1)}%`:'0%';$('timelineTitle').textContent=`直近${formatDuration(windowMinutes)}のコメント数推移`;renderAvailableSpan();renderTimeline();renderUsers(gs);if(selected)renderDetail(selected);}
function renderAvailableSpan(){if(!storedComments.length){$('availableSpan').textContent='保存データなし';return;}const times=storedComments.map(commentTime).filter(Boolean);if(!times.length){$('availableSpan').textContent='保存データなし';return;}const oldest=Math.min(...times),newest=Math.max(...times);const mins=Math.max(1,Math.round((newest-oldest)/60000));$('availableSpan').textContent=`保存中: ${formatDuration(mins)} / ${storedComments.length}件`;}
function renderUsers(gs){const q=$('search').value.toLowerCase();$('usersBody').innerHTML=gs.filter(g=>!q||g.userId.toLowerCase().includes(q)||g.list.some(c=>String(c.message||'').toLowerCase().includes(q))).map(g=>`<tr data-user="${escapeHtml(g.userId)}"><td>${escapeHtml(g.userId)}</td><td>${g.count}</td><td>${comments.length?(g.count/comments.length*100).toFixed(1):0}%</td><td>${avgGap(g.list)}</td><td><button class="mute" data-mute="${escapeHtml(g.userId)}">${mutedUsers.includes(g.userId)?'解除':'ミュート'}</button></td></tr>`).join('');document.querySelectorAll('tr[data-user]').forEach(tr=>tr.onclick=e=>{if(e.target.dataset.mute)return;selected=tr.dataset.user;renderDetail(selected);});document.querySelectorAll('[data-mute]').forEach(b=>b.onclick=async e=>{e.stopPropagation();await toggleMute(b.dataset.mute);});}
async function toggleMute(uid){const set=new Set(mutedUsers);set.has(uid)?set.delete(uid):set.add(uid);mutedUsers=[...set];await chrome.storage.local.set({mutedUsers});render();}
function renderDetail(uid){const list=comments.filter(c=>String(c.userId)===uid).sort((a,b)=>commentTime(a)-commentTime(b));$('detailTitle').textContent=uid;$('detailMeta').innerHTML=`${list.length}件 / 平均間隔 ${avgGap(list)} <button class="mute" id="detailMute">${mutedUsers.includes(uid)?'ミュート解除':'この投稿者をミュート'}</button>`;$('detailComments').innerHTML=list.map(c=>`<div class="comment"><span class="time">${new Date(commentTime(c)).toLocaleTimeString()}</span><span class="msg">${escapeHtml(c.message)}</span></div>`).join('');$('detailMute').onclick=()=>toggleMute(uid);}
function renderTimeline(){const cv=$('timeline'),ctx=cv.getContext('2d');const w=cv.width,h=cv.height;ctx.clearRect(0,0,w,h);const binCount=12,bins=Array(binCount).fill(0),now=Date.now(),span=windowMinutes*60000,binMs=span/binCount;for(const c of comments){const age=now-commentTime(c);const idx=binCount-1-Math.floor(age/binMs);if(idx>=0&&idx<binCount)bins[idx]++;}const max=Math.max(1,...bins);ctx.fillStyle='#ccc';ctx.font='12px system-ui';for(let i=0;i<binCount;i++){const x=40+i*((w-60)/(binCount-1)),barH=(bins[i]/max)*(h-55);ctx.fillRect(x-12,h-28-barH,24,barH);ctx.fillText(String(bins[i]),x-7,h-34-barH);ctx.fillStyle='#777';const remaining=Math.round(windowMinutes-(i*(windowMinutes/(binCount-1))));const label=remaining>=60?`${(remaining/60).toFixed(remaining%60?1:0)}h`:`${remaining}m`;ctx.fillText(label,x-14,h-8);ctx.fillStyle='#ccc';}}
function renderHistoryStatus(p){const el=$('historyStatus');if(!p){el.textContent='過去コメントを取得する場合は、ABEMAでコメント欄を表示した状態で「過去コメントを読み込む」を押してください。';$('cancelHistory').style.display='none';return;}const running=p.status==='running';$('cancelHistory').style.display=running?'inline-block':'none';const oldest=p.oldestAt?` / 最古 ${new Date(p.oldestAt).toLocaleTimeString()}`:'';el.textContent=`${p.message||p.status}${oldest}`;}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('applyWindow').onclick=async()=>{windowMinutes=currentWindowFromControls();await chrome.storage.local.set({analysisWindowMinutes:windowMinutes});syncControlsFromMinutes(windowMinutes);applyFilter();};
$('loadHistory').onclick=async()=>{const id=Date.now();await chrome.storage.local.set({historyLoadProgress:{status:'starting',requestId:id,message:'ABEMAタブへ開始指示を送信中…',updatedAt:id},historyLoadRequest:id});renderHistoryStatus({status:'starting',message:'ABEMAタブへ開始指示を送信中…'});};
$('cancelHistory').onclick=async()=>{await chrome.storage.local.set({historyLoadCancel:Date.now()});};
$('refresh').onclick=load;$('search').oninput=()=>renderUsers(groups());$('exportJson').onclick=()=>download('abema-comments.json',JSON.stringify(comments,null,2),'application/json');$('exportCsv').onclick=()=>{const q=s=>`"${String(s??'').replaceAll('"','""')}"`;download('abema-comments.csv',['time,userId,message,pageTitle',...comments.map(c=>[new Date(commentTime(c)).toISOString(),c.userId,c.message,c.pageTitle].map(q).join(','))].join('\n'),'text/csv');};chrome.storage.onChanged.addListener((c,a)=>{if(a!=='local')return;if(c.comments||c.mutedUsers)load();if(c.historyLoadProgress)renderHistoryStatus(c.historyLoadProgress.newValue);});load();
